apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset
  namespace: infra
spec:
  generators:
  - git:
      repoURL: https://github.com/stealur/argocd-topology.git
      revision: HEAD
      files:
      - path: "helm-values-files/**/*.yaml"
  template:
    metadata:
      name: '{{ jbg.namespace }}'
    spec:
      destination:
        namespace: '{{ jbg.namespace }}'
        server: https://kubernetes.default.svc
      project: '{{ jbg.namespace }}'
      source:
        path: "./"
        repoURL: https://github.com/stealur/argocd-topology.git
        targetRevision: HEAD
        helm:
          valueFiles:
            - "{{ filepath }}"
      syncPolicy:
        automated:
          prune: true
          seflHeal: true
